# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # for IP camera as webcam
  boot.kernelModules = [ "v4l2loopback" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    v4l2loopback
  ];
  boot.extraModprobeConfig = ''
    options v4l2loopback exclusive_caps=1 devices=1
  '';

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/85485197-e6f7-498d-8b38-f3c5a1e92137";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/24F4-2610";
      fsType = "vfat";
    };

  # mount windows boot partition so os-prober finds it
  fileSystems."/boot-win" =
    { device = "/dev/disk/by-uuid/2A6C-3479";
      fsType = "vfat";
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/7365130763304B2D";
      fsType = "ntfs";
      options = [ "uid=1000" "gid=100" ];
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
