# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  # boot.kernelModules = [ "kvm-amd" ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/b36d6d6b-a4f8-4ba4-af67-ee3c9e8f4cdf";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A6C-3479";
      fsType = "vfat";
    };
  
  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/2432CF0932CEDEC4";
      fsType = "ntfs";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 16;
}
